
export const id = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(3) > td.tdlb"
export const prenom = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(4) > td.tdlb > strong"
export const nom = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(5) > td.tdl > b"
export const sexe = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(6) > td.tdl"
export const metier = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(7) > td.tdl"
export const naissance = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(8) > td.tdl"
export const villeNaissance = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(9) > td.tdl"
export const paysNaissance = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(10) > td.tdl"
export const bapteme = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(11) > td.tdref"
export const deces = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(12) > td.tdl"
export const villeDeces = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(13) > td.tdl"
export const paysDeces = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(14) > td.tdl"
export const inhumation = "#form1 > div.content > table:nth-child(6) > tbody > tr > td:nth-child(1) > table > tbody > tr:nth-child(15) > td.tdref"
export const photo = "#imgPersonPhoto"
export const pere = "#hlnkFather"
export const mere = "#hlnkMother"